# Project information
site_name: Algemene Regelgeving CombatGain
site_url: 'https://wetboek.combatgain.nl/'
site_description: 'Wet en regelgeving van CombatGain'
site_author: 'John'

# Copyright
copyright: Copyright &copy; 2026 CombatGain

# Congiguration
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: img/favicon.png
  logo: img/logo.png
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md
  - Eiland Regelgeving: eiland.md
  - Voertuigklasses: offroad.md
  
extra_css:
  - stylesheets/extra.css